// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthInviteInfo(arg1:string,arg2:string):Promise<main.InviteInfo>;

export function AuthLogin(arg1:string,arg2:string,arg3:string):Promise<main.AuthResult>;

export function AuthRedeemInvite(arg1:string,arg2:string,arg3:string):Promise<main.AuthResult>;

export function AuthSignOut(arg1:string):Promise<void>;

export function ClearPendingInvite():Promise<void>;

export function GetCookies(arg1:string):Promise<string>;

export function GetDataPath():Promise<string>;

export function GetEnvironments(arg1:string):Promise<string>;

export function GetPendingInvite():Promise<main.PendingInvite>;

export function GetProjects(arg1:string):Promise<string>;

export function GetSession(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function ListRemoteProfiles():Promise<string>;

export function ParseInviteURL(arg1:string):Promise<main.PendingInvite>;

export function SaveCookies(arg1:string,arg2:string):Promise<void>;

export function SaveEnvironments(arg1:string,arg2:string):Promise<void>;

export function SaveProjects(arg1:string,arg2:string):Promise<void>;

export function SaveSession(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SendRequest(arg1:main.HTTPRequest):Promise<main.HTTPResponse>;

export function SetClipboard(arg1:string):Promise<void>;

export function SetPendingInvite(arg1:string):Promise<void>;

export function SyncRemoteProjects(arg1:string):Promise<string>;
