// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthInviteInfo(arg1, arg2) {
  return window['go']['main']['App']['AuthInviteInfo'](arg1, arg2);
}

export function AuthLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthLogin'](arg1, arg2, arg3);
}

export function AuthRedeemInvite(arg1, arg2, arg3) {
  return window['go']['main']['App']['AuthRedeemInvite'](arg1, arg2, arg3);
}

export function AuthSignOut(arg1) {
  return window['go']['main']['App']['AuthSignOut'](arg1);
}

export function ClearPendingInvite() {
  return window['go']['main']['App']['ClearPendingInvite']();
}

export function GetCookies(arg1) {
  return window['go']['main']['App']['GetCookies'](arg1);
}

export function GetDataPath() {
  return window['go']['main']['App']['GetDataPath']();
}

export function GetEnvironments(arg1) {
  return window['go']['main']['App']['GetEnvironments'](arg1);
}

export function GetPendingInvite() {
  return window['go']['main']['App']['GetPendingInvite']();
}

export function GetProjects(arg1) {
  return window['go']['main']['App']['GetProjects'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListRemoteProfiles() {
  return window['go']['main']['App']['ListRemoteProfiles']();
}

export function ParseInviteURL(arg1) {
  return window['go']['main']['App']['ParseInviteURL'](arg1);
}

export function SaveCookies(arg1, arg2) {
  return window['go']['main']['App']['SaveCookies'](arg1, arg2);
}

export function SaveEnvironments(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvironments'](arg1, arg2);
}

export function SaveProjects(arg1, arg2) {
  return window['go']['main']['App']['SaveProjects'](arg1, arg2);
}

export function SaveSession(arg1, arg2) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetClipboard(arg1) {
  return window['go']['main']['App']['SetClipboard'](arg1);
}

export function SetPendingInvite(arg1) {
  return window['go']['main']['App']['SetPendingInvite'](arg1);
}

export function SyncRemoteProjects(arg1) {
  return window['go']['main']['App']['SyncRemoteProjects'](arg1);
}
